version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=merchuser
      - DB_PASSWORD=merchpass
      - DB_NAME=merchshop
      - JWT_SECRET=Leonid_Odintsov
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: merchshop
      POSTGRES_USER: merchuser
      POSTGRES_PASSWORD: merchpass
    ports:
      - "5432:5432"
